Repository Cloud-Engineering2/project1-team3, pull requests merged in 2024-12, with the labels that each got.

#4 Feat: post 도메인 기본 컴포넌트 추가
  src/main/java/com/board/controller/PostController.java
  src/main/java/com/board/repository/PostRepository.java
  src/main/java/com/board/service/PostService.java
Labels: ⚙️ Setting

#5 Feat: comment-domain-setting
  src/main/java/com/board/controller/CommentController.java
  src/main/java/com/board/repository/CommentRepository.java
  src/main/java/com/board/service/CommentService.java
Labels: ⚙️ Setting

#6 Feat: 엔티티 생성
  src/main/java/com/board/constant/Category.java
  src/main/java/com/board/entity/Comment.java
  src/main/java/com/board/entity/Post.java
  src/main/java/com/board/repository/CommentRepository.java
  src/main/java/com/board/repository/PostRepository.java
Labels: ✨ Feature, ⚙️ Setting

#8 Feat: Post 생성 및 전체 조회 API 구현
  src/main/java/com/board/controller/PostController.java
  src/main/java/com/board/dto/request/PostRequest.java
  src/main/java/com/board/dto/response/PostResponse.java
  src/main/java/com/board/entity/AuditingFields.java
  src/main/java/com/board/entity/Post.java
  src/main/java/com/board/exception/GlobalExceptionHandler.java
  src/main/java/com/board/service/PostService.java
Labels: ✨ Feature

#10 Refactor: userId 타입 변경
  src/main/java/com/board/controller/CommentController.java
  src/main/java/com/board/repository/UserRepository.java
  src/main/java/com/board/service/CommentService.java
Labels: 🔨 Refactor

#11 Feat: post 수정 API 추가
  src/main/java/com/board/controller/PostController.java
  src/main/java/com/board/entity/Post.java
  src/main/java/com/board/exception/GlobalExceptionHandler.java
  src/main/java/com/board/exception/PostNotFoundException.java
  src/main/java/com/board/service/PostService.java
Labels: ✨ Feature

#12 Feat: Post 삭제 API 구현
  src/main/java/com/board/controller/PostController.java
  src/main/java/com/board/service/PostService.java
Labels: ✨ Feature

#15 Feat : user-signup
  pom.xml
  src/main/java/com/board/config/JpaConfig.java
  src/main/java/com/board/config/SecurityConfig.java
  src/main/java/com/board/controller/UserController.java
  src/main/java/com/board/dto/security/PrincipalDetails.java
  src/main/java/com/board/service/UserService.java
  src/main/resources/templates/userInfo.html
  target/classes/templates/userInfo.html
Labels: 🔨 Refactor, ✨ Feature

#18 Docs: gitignore 설정 추가
  .gitignore
Labels: 📑 Docs

#20 Feat: Post에 유저 추가
  src/main/java/com/board/common/ErrorResponse.java
  src/main/java/com/board/common/SuccessResponse.java
  src/main/java/com/board/common/base/BaseResponse.java
  src/main/java/com/board/controller/PostController.java
  src/main/java/com/board/exception/GlobalExceptionHandler.java
  src/main/java/com/board/exception/UnauthorizeException.java
  src/main/java/com/board/service/PostService.java
Labels: 🔨 Refactor, ✨ Feature

#21 refactor : UserInfo 페이지 thymeleaf 적용
  src/main/java/com/board/controller/UserController.java
  src/main/java/com/board/service/UserService.java
  src/main/resources/templates/userInfo.html
Labels: 🔨 Refactor

#24 Feat: 카테고리 화면 출력
  src/main/resources/templates/post/postDetail.html
  src/main/resources/templates/post/posts.html
  target/classes/templates/post/postDetail.html
  target/classes/templates/post/posts.html
Labels: ✨ Feature, 🎨 Front

#25 Feat: Comment 프론트 연결
  src/main/java/com/board/controller/CommentController.java
  src/main/java/com/board/service/CommentService.java
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/post/postDetail.html
  src/main/resources/templates/userInfo.html
  target/classes/templates/layout/header.html
  target/classes/templates/post/postDetail.html
  target/classes/templates/userInfo.html
Labels: ✨ Feature, 🎨 Front
